[workspace]
resolver = "2"

members = [
    "leptos-pavex",
    "leptos-pavex-macro"
]

[workspace.dependencies]
pavex = "0.1.38"
futures = "0.3.30"
url = "2.5.0"
bytes = "1.6.0"
leptos = { version = "0.7.0-preview2", features = ["ssr"] }
leptos_integration_utils = { git="https://github.com/leptos-rs/leptos", branch="leptos_0.7" }
leptos_meta = { version = "0.7.0-preview2", features = ["ssr"] }
leptos_router = { version = "0.7.0-preview2", features = ["ssr"] }